name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Deploy to production
      run: echo 'Deploying to production...'
